### ISSUE TITLE
No https support

### ISSUE THREAD

**Issue by jumpingmushroom** [jghaanstra/tv.video.sonarr.radarr#10]
Hi!

I would love to use your app, but unfortunately it seems your app does'nt support communication through a proxy. Is there any plans on implementing support for this?

I get this message: Error: network timeout at: http://subdomain.example.com:443/api/rootfolder which leads me to believe that even though it's using 443, it's not doing the request in https.

Hope you get time to look into this. I've isolated my IOT devices and my DMZ network and stopped exposing ports on the host OS for containers, so encrypted communication would be ideal.

Cheers!

/Jumpingmushroom

**Comment by jghaanstra** [comment]
No plans yet but I'll consider this a feature request and will look into it when I have time.

**Comment by jumpingmushroom** [comment]
Thank you for the quick response. I've opened the port and firewall betwen the two devices for now as a workaround and that seems to do the job. But ssl support would of course be the best option.

**Comment by jghaanstra** [comment]
Fixed with release 2.1.1 which is pending approval in the app store.

https://github.com/jghaanstra/tv.video.sonarr.radarr/releases/tag/2.1.1
