### ISSUE TITLE
[FEATURE] Add 0 to Season and Episode

### ISSUE THREAD

**Issue by ghost** [jghaanstra/tv.video.sonarr.radarr#4]
When sending a push or else #season and #episode return 1 2 3 etc..
I would love to see that it adds a 0 before the season or episode nummer if below 10.

Example: S01E03 instead of S1E3

**Comment by jghaanstra** [comment]
Implemented in release 1.1.1: https://github.com/jghaanstra/tv.video.sonarr.radarr/releases/tag/1.1.1
