### ISSUE TITLE
[FEATURE] Add health trigger card

### ISSUE THREAD

**Issue by luguber** [jghaanstra/tv.video.sonarr.radarr#9]
Checking for the posibility to add a health trigger card for both Sonarr and Radarr (and possible Lidarr if that gets supported).
And a tag for which health issue it is detecting. 
For example, lost connection with indexer or download client. Or network drive not available.

**Comment by jghaanstra** [comment]
Sonarr and Radarr do not supply this information through the webhook functionality. Although Lidarr seems to have this as an option for some notification services it's also not available through the webhook functionality.

So I dont see this happening unless Sonarr, Radarr and Lidarr implement this functionality.
